<style>
	img[alt="line"] {
		display: none !important;
	}
	
	.factbox{
		background: #F5F5F5;
		max-width: 624px;
		padding: 12px 0 8px 0;
		margin: 8px auto;
		border-bottom: 2px solid #CCC;
		border-top: 2px solid #CCC;
	}
	.factbox h1, .factbox h2, .factbox .cross-head{
		text-align: center;
	}
	.factbox img, .factbox .full-width{
		width: 100%;
		margin-right: 0;
		margin-left: 0;
	}
	.factbox p{
		margin-left: 8px;
		margin-right: 8px;
	}
</style>
<div class="factbox">