<!-- newspec-9601/centering/before.inc -->
<style>
	.blq-container-outer .generic--centering__NEWSSPEC9061{
		max-width : 624px;
		display: block;
		margin : 0 auto 18px;
	}

	.blq-container-outer .generic--centering__NEWSSPEC9061{
		margin: 0 auto;
	}
	.blq-container-outer .generic--centering__NEWSSPEC9061 .cross-head{
		display: block;
		text-align: center;
	}
</style>

<span class="generic--centering__NEWSSPEC9061">